# yaml-language-server: $schema=../policy.schema.json
apiVersion: v1
kind: policy
metadata:
  name: apim-to-container-apps
  category: integration
  services: [api-management, container-apps]
  last_reviewed: "2025-12-01"

rules:
  - id: INT-001
    severity: required
    description: "Route all external API traffic through API Management"
    rationale: "Centralizes auth, rate limiting, and observability"
    applies_to: [cloud-architect, terraform-agent, bicep-agent, biz-analyst]
    template_check:
      require_service: [api-management]
      when_services_present: [container-apps]
      severity: warning
      error_message: "Template has container-apps but no api-management gateway"

  - id: INT-002
    severity: required
    description: "Use APIM managed identity to authenticate to Container Apps"
    rationale: "No shared keys or certificates between services"
    applies_to: [cloud-architect, terraform-agent, bicep-agent]
    template_check:
      scope: [api-management]
      when_services_present: [container-apps]
      require_config: [identity]
      error_message: "Service '{service_name}' ({service_type}) missing managed identity for authenticating to Container Apps"

  - id: INT-003
    severity: recommended
    description: "Set Container App ingress to internal-only when fronted by APIM"
    rationale: "Container App should not be directly accessible from the internet"
    applies_to: [cloud-architect, terraform-agent, bicep-agent]
    template_check:
      scope: [container-apps]
      when_services_present: [api-management]
      require_config_value:
        ingress: internal
      error_message: "Service '{service_name}' ({service_type}) should set ingress: internal when APIM is the external gateway"

  - id: INT-004
    severity: recommended
    description: "Configure APIM caching policies for read-heavy endpoints"
    rationale: "Reduces backend load and improves response latency"
    applies_to: [cloud-architect, app-developer]
    template_check:
      scope: [api-management]
      when_services_present: [container-apps]
      require_config: [caching]
      error_message: "Service '{service_name}' ({service_type}) missing caching: true for read-heavy endpoints"

patterns:
  - name: "APIM backend with managed identity"
    description: "Configure APIM backend pointing to internal Container App"
    example: |
      resource "azurerm_api_management_backend" "container_app" {
        name                = "container-app-backend"
        resource_group_name = azurerm_resource_group.main.name
        api_management_name = azurerm_api_management.main.name
        protocol            = "http"
        url                 = "https://${azurerm_container_app.api.latest_revision_fqdn}"
      }

anti_patterns:
  - description: "Do not expose Container App endpoints directly to the internet"
    instead: "Use APIM as the gateway; set Container App ingress to internal"

references:
  - title: "APIM with Container Apps"
    url: "https://learn.microsoft.com/azure/api-management/integrate-container-app"
